[build]
  publish = "public"
  functions = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/nossl/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/nossl/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    # Disable HTTP to HTTPS redirect for this path
    Netlify-Force-HTTPS = "false"
