[build]
  publish = "."  # Deploy the root directory as the site
  functions = "functions"  # Where your serverless functions live

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
